# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190312_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={},
        ),
    ]
